title: check
#profile_img: assets/img/profile.jpg
#icon_img: assets/img/icon.webp

name: " check"
#job: "〈MSc Student | WIS〉"

#phone_number: 07777777777
#address: Rehovot, Israel
#email: faratj.mazal@gmail.com
#linkedin_username: Mazal Faraj
#github_username: mazalik
#instagram_username: mazalfaraj
#twitter_username: twitter
#facebook_username: Mazal Faraj
#youtube_username: youtube
#blog_url: homepage-url

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
