title: check
#profile_img: assets/img/profile.jpg
#icon_img: assets/img/icon.webp

name: "Cream and Crust"
job: "Authentic mama's bakery"

phone_number: 0652341526
address: Jerusalem, Israel
email: cream.an.crust@gmail.com
github_username: Creamandcrust.github.io
linkedin_username:  chack
instagram_username: check
twitter_username: check
facebook_username: check 
youtube_username: youtube
blog_url: homepage-url
baseurl: /Creamandcrust.github.io
url: https://Creamandcrust.github.io


exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
